### ISSUE TITLE
GetValues

### ISSUE THREAD

**Issue by DJWassink** [JBlaak/Bonn-Form#1]
De didmount  in een listener luister naar wijzigingen waarna het daarna de get values gebruikt. Kan de value van de callback niet gewoon gebruikt worden?

**Comment by JBlaak** [comment]
je kan op meerdere velden luisteren maar je luistert per veld ,je wil alle waarden mee geven waar op geluisterd wordt dus heb vraag je alle waarden opnieuw op. Of je zou een kopie moeten opslaan..
